name: InfraCI - Fork PR Validation

on:
  pull_request:
    branches: [main, develop]

env:
  AZCLIVERSION: 2.29.2 #Pinning to a specific AZ CLI version

jobs:
  Validation:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v2

      - name: Job parameter check
        run: |
          echo "EventTrigger name is ${{github.event_name}}"
          echo "PR obj is ${{toJson(github.event.pull_request)}}"
          echo "Is fork? ${{ github.event.pull_request.head.repo.fork }}"
          
      - name: Welcome the forker
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Write-Output "Welcome Mr Forky"
          $PRId="${{ github.event.pull_request.number }}"
          
          gh pr comment $PRId --body "PR origin is from fork - thanks for the contribution!"
          
      - name: Add labels to PR that signal forked and full testing required
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $PRId="${{ github.event.pull_request.number }}"
          
          #if changes to bicep
          gh pr edit $PRId --add-label "requires-full-validation,do-not-merge"
          
          #gh pr edit $PRId --add-label do-not-merge
          
      - name: List files changed in this PR
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $PRId="${{ github.event.pull_request.number }}"
          
          $files=gh pr view $PRId --json files --jq '.files.[].path'
          
          write-output $files
  
